1 mt940 naar xml
INF2-3/parser pull request #4
Opened 2023-03-17 11:13 UTC by Jessev3

2023-03-17 13:13 UTC, Mappeldorn approved these changes

2023-03-18 14:44 UTC, FrancaBaars requested changes

2023-03-18 14:44 UTC, FrancaBaars commented on src/main/java/com/api/parser/controller/XMLController.java
> +import org.springframework.web.bind.annotation.RequestMapping;
De ongebruikte imports graag weghalen

2023-03-18 14:44 UTC, FrancaBaars commented on src/main/java/com/api/parser/parser/Parser.java
Auto formatter graag nog even over dit bestand halen.

2023-03-20 13:25 UTC, FrancaBaars approved these changes

2023-03-20 13:25 UTC, merged